export type Hsk1Character = {
  id: string
  character: string
  pinyin: string
  definition: string
}

export const Hsk1Characters: Hsk1Character[] = [
  { id: "hsk1-word-爱", character: "爱", pinyin: "ài", definition: "love; like" },
  { id: "hsk1-word-八", character: "八", pinyin: "bā", definition: "eight" },
  { id: "hsk1-word-爸爸", character: "爸爸", pinyin: "bà ba", definition: "father; dad" },
  { id: "hsk1-word-北京", character: "北京", pinyin: "běi jīng", definition: "Beijing" },
  { id: "hsk1-word-杯子", character: "杯子", pinyin: "bēi zi", definition: "cup; glass" },
  { id: "hsk1-word-本", character: "本", pinyin: "běn", definition: "classifier for books; volume" },
  { id: "hsk1-word-不", character: "不", pinyin: "bù", definition: "not; no" },
  { id: "hsk1-word-不客气", character: "不客气", pinyin: "bú kè qi", definition: "you're welcome; don't mention it" },
  { id: "hsk1-word-菜", character: "菜", pinyin: "cài", definition: "dish; vegetable" },
  { id: "hsk1-word-茶", character: "茶", pinyin: "chá", definition: "tea" },
  { id: "hsk1-word-吃", character: "吃", pinyin: "chī", definition: "eat" },
  { id: "hsk1-word-出租车", character: "出租车", pinyin: "chū zū chē", definition: "taxi; cab" },
  { id: "hsk1-word-大", character: "大", pinyin: "dà", definition: "big; large" },
  { id: "hsk1-word-打电话", character: "打电话", pinyin: "dǎ diàn huà", definition: "call; make a phone call" },
  { id: "hsk1-word-的", character: "的", pinyin: "de", definition: "of; possessive particle" },
  { id: "hsk1-word-点", character: "点", pinyin: "diǎn", definition: "o'clock; point; dot; a little" },
  { id: "hsk1-word-电脑", character: "电脑", pinyin: "diàn nǎo", definition: "computer" },
  { id: "hsk1-word-电视", character: "电视", pinyin: "diàn shì", definition: "television; TV" },
  { id: "hsk1-word-电影", character: "电影", pinyin: "diàn yǐng", definition: "movie; film" },
  { id: "hsk1-word-东西", character: "东西", pinyin: "dōng xi", definition: "thing; stuff" },
  { id: "hsk1-word-都", character: "都", pinyin: "dōu", definition: "all; both" },
  { id: "hsk1-word-读", character: "读", pinyin: "dú", definition: "read; study" },
  { id: "hsk1-word-对不起", character: "对不起", pinyin: "duì bu qǐ", definition: "sorry; excuse me" },
  { id: "hsk1-word-多", character: "多", pinyin: "duō", definition: "many; much" },
  { id: "hsk1-word-多少", character: "多少", pinyin: "duō shǎo", definition: "how much; how many" },
  { id: "hsk1-word-二", character: "二", pinyin: "èr", definition: "two" },
  { id: "hsk1-word-儿子", character: "儿子", pinyin: "ér zi", definition: "son" },
  { id: "hsk1-word-饭店", character: "饭店", pinyin: "fàn diàn", definition: "restaurant" },
  { id: "hsk1-word-飞机", character: "飞机", pinyin: "fēi jī", definition: "airplane; plane" },
  { id: "hsk1-word-分钟", character: "分钟", pinyin: "fēn zhōng", definition: "minute" },
  { id: "hsk1-word-高兴", character: "高兴", pinyin: "gāo xìng", definition: "happy; glad" },
  { id: "hsk1-word-个", character: "个", pinyin: "gè", definition: "general classifier" },
  { id: "hsk1-word-工作", character: "工作", pinyin: "gōng zuò", definition: "work; job" },
  { id: "hsk1-word-狗", character: "狗", pinyin: "gǒu", definition: "dog" },
  { id: "hsk1-word-汉语", character: "汉语", pinyin: "hàn yǔ", definition: "Chinese language" },
  { id: "hsk1-word-号", character: "号", pinyin: "hào", definition: "date; number" },
  { id: "hsk1-word-好", character: "好", pinyin: "hǎo", definition: "good; well" },
  { id: "hsk1-word-和", character: "和", pinyin: "hé", definition: "and; with" },
  { id: "hsk1-word-喝", character: "喝", pinyin: "hē", definition: "drink" },
  { id: "hsk1-word-很", character: "很", pinyin: "hěn", definition: "very; quite" },
  { id: "hsk1-word-后面", character: "后面", pinyin: "hòu miàn", definition: "behind; back" },
  { id: "hsk1-word-会", character: "会", pinyin: "huì", definition: "can; know how to" },
  { id: "hsk1-word-回", character: "回", pinyin: "huí", definition: "return; go back" },
  { id: "hsk1-word-几", character: "几", pinyin: "jǐ", definition: "how many; a few" },
  { id: "hsk1-word-家", character: "家", pinyin: "jiā", definition: "home; family" },
  { id: "hsk1-word-叫", character: "叫", pinyin: "jiào", definition: "be called; call" },
  { id: "hsk1-word-今天", character: "今天", pinyin: "jīn tiān", definition: "today" },
  { id: "hsk1-word-九", character: "九", pinyin: "jiǔ", definition: "nine" },
  { id: "hsk1-word-开", character: "开", pinyin: "kāi", definition: "open; turn on; start" },
  { id: "hsk1-word-看", character: "看", pinyin: "kàn", definition: "look; watch; read" },
  { id: "hsk1-word-看见", character: "看见", pinyin: "kàn jiàn", definition: "see; catch sight of" },
  { id: "hsk1-word-块", character: "块", pinyin: "kuài", definition: "piece; chunk; yuan" },
  { id: "hsk1-word-来", character: "来", pinyin: "lái", definition: "come; arrive" },
  { id: "hsk1-word-老师", character: "老师", pinyin: "lǎo shī", definition: "teacher" },
  { id: "hsk1-word-了", character: "了", pinyin: "le", definition: "completed-action particle" },
  { id: "hsk1-word-冷", character: "冷", pinyin: "lěng", definition: "cold" },
  { id: "hsk1-word-里", character: "里", pinyin: "lǐ", definition: "inside; in" },
  { id: "hsk1-word-六", character: "六", pinyin: "liù", definition: "six" },
  { id: "hsk1-word-吗", character: "吗", pinyin: "ma", definition: "question particle" },
  { id: "hsk1-word-买", character: "买", pinyin: "mǎi", definition: "buy" },
  { id: "hsk1-word-妈妈", character: "妈妈", pinyin: "mā ma", definition: "mother; mom" },
  { id: "hsk1-word-猫", character: "猫", pinyin: "māo", definition: "cat" },
  { id: "hsk1-word-没关系", character: "没关系", pinyin: "méi guān xi", definition: "it's okay; it doesn't matter" },
  { id: "hsk1-word-没有", character: "没有", pinyin: "méi yǒu", definition: "not have; there is not" },
  { id: "hsk1-word-米饭", character: "米饭", pinyin: "mǐ fàn", definition: "cooked rice" },
  { id: "hsk1-word-明天", character: "明天", pinyin: "míng tiān", definition: "tomorrow" },
  { id: "hsk1-word-名字", character: "名字", pinyin: "míng zi", definition: "name" },
  { id: "hsk1-word-那", character: "那", pinyin: "nà", definition: "that" },
  { id: "hsk1-word-哪", character: "哪", pinyin: "nǎ", definition: "which" },
  { id: "hsk1-word-哪儿", character: "哪儿", pinyin: "nǎ er", definition: "where" },
  { id: "hsk1-word-呢", character: "呢", pinyin: "ne", definition: "sentence particle" },
  { id: "hsk1-word-能", character: "能", pinyin: "néng", definition: "can; be able to" },
  { id: "hsk1-word-你", character: "你", pinyin: "nǐ", definition: "you" },
  { id: "hsk1-word-年", character: "年", pinyin: "nián", definition: "year" },
  { id: "hsk1-word-女儿", character: "女儿", pinyin: "nǚ ér", definition: "daughter" },
  { id: "hsk1-word-朋友", character: "朋友", pinyin: "péng you", definition: "friend" },
  { id: "hsk1-word-漂亮", character: "漂亮", pinyin: "piào liang", definition: "beautiful; pretty" },
  { id: "hsk1-word-苹果", character: "苹果", pinyin: "píng guǒ", definition: "apple" },
  { id: "hsk1-word-七", character: "七", pinyin: "qī", definition: "seven" },
  { id: "hsk1-word-钱", character: "钱", pinyin: "qián", definition: "money" },
  { id: "hsk1-word-前面", character: "前面", pinyin: "qián miàn", definition: "front; in front" },
  { id: "hsk1-word-请", character: "请", pinyin: "qǐng", definition: "please; invite" },
  { id: "hsk1-word-去", character: "去", pinyin: "qù", definition: "go" },
  { id: "hsk1-word-热", character: "热", pinyin: "rè", definition: "hot" },
  { id: "hsk1-word-人", character: "人", pinyin: "rén", definition: "person; people" },
  { id: "hsk1-word-认识", character: "认识", pinyin: "rèn shi", definition: "know; recognize" },
  { id: "hsk1-word-三", character: "三", pinyin: "sān", definition: "three" },
  { id: "hsk1-word-上", character: "上", pinyin: "shàng", definition: "up; on; above" },
  { id: "hsk1-word-商店", character: "商店", pinyin: "shāng diàn", definition: "store; shop" },
  { id: "hsk1-word-上午", character: "上午", pinyin: "shàng wǔ", definition: "morning" },
  { id: "hsk1-word-少", character: "少", pinyin: "shǎo", definition: "few; little" },
  { id: "hsk1-word-谁", character: "谁", pinyin: "shéi", definition: "who" },
  { id: "hsk1-word-什么", character: "什么", pinyin: "shén me", definition: "what" },
  { id: "hsk1-word-是", character: "是", pinyin: "shì", definition: "be; is; are; am" },
  { id: "hsk1-word-十", character: "十", pinyin: "shí", definition: "ten" },
  { id: "hsk1-word-时候", character: "时候", pinyin: "shí hou", definition: "time; moment" },
  { id: "hsk1-word-书", character: "书", pinyin: "shū", definition: "book" },
  { id: "hsk1-word-水", character: "水", pinyin: "shuǐ", definition: "water" },
  { id: "hsk1-word-水果", character: "水果", pinyin: "shuǐ guǒ", definition: "fruit" },
  { id: "hsk1-word-睡觉", character: "睡觉", pinyin: "shuì jiào", definition: "sleep; go to bed" },
  { id: "hsk1-word-说", character: "说", pinyin: "shuō", definition: "speak; say" },
  { id: "hsk1-word-四", character: "四", pinyin: "sì", definition: "four" },
  { id: "hsk1-word-岁", character: "岁", pinyin: "suì", definition: "years old; age classifier" },
  { id: "hsk1-word-他", character: "他", pinyin: "tā", definition: "he; him" },
  { id: "hsk1-word-她", character: "她", pinyin: "tā", definition: "she; her" },
  { id: "hsk1-word-太", character: "太", pinyin: "tài", definition: "too; overly" },
  { id: "hsk1-word-天气", character: "天气", pinyin: "tiān qì", definition: "weather" },
  { id: "hsk1-word-听", character: "听", pinyin: "tīng", definition: "listen; hear" },
  { id: "hsk1-word-同学", character: "同学", pinyin: "tóng xué", definition: "classmate" },
  { id: "hsk1-word-喂", character: "喂", pinyin: "wèi", definition: "hello (on the phone)" },
  { id: "hsk1-word-我", character: "我", pinyin: "wǒ", definition: "I; me" },
  { id: "hsk1-word-我们", character: "我们", pinyin: "wǒ men", definition: "we; us" },
  { id: "hsk1-word-五", character: "五", pinyin: "wǔ", definition: "five" },
  { id: "hsk1-word-下", character: "下", pinyin: "xià", definition: "down; below; under" },
  { id: "hsk1-word-想", character: "想", pinyin: "xiǎng", definition: "want; think; would like" },
  { id: "hsk1-word-先生", character: "先生", pinyin: "xiān sheng", definition: "Mr.; sir" },
  { id: "hsk1-word-现在", character: "现在", pinyin: "xiàn zài", definition: "now" },
  { id: "hsk1-word-小", character: "小", pinyin: "xiǎo", definition: "small; little" },
  { id: "hsk1-word-小姐", character: "小姐", pinyin: "xiǎo jie", definition: "Miss; young lady" },
  { id: "hsk1-word-下午", character: "下午", pinyin: "xià wǔ", definition: "afternoon" },
  { id: "hsk1-word-下雨", character: "下雨", pinyin: "xià yǔ", definition: "rain; to rain" },
  { id: "hsk1-word-些", character: "些", pinyin: "xiē", definition: "some; a few" },
  { id: "hsk1-word-写", character: "写", pinyin: "xiě", definition: "write" },
  { id: "hsk1-word-谢谢", character: "谢谢", pinyin: "xiè xie", definition: "thank you; thanks" },
  { id: "hsk1-word-喜欢", character: "喜欢", pinyin: "xǐ huan", definition: "like; enjoy" },
  { id: "hsk1-word-星期", character: "星期", pinyin: "xīng qī", definition: "week" },
  { id: "hsk1-word-学生", character: "学生", pinyin: "xué sheng", definition: "student" },
  { id: "hsk1-word-学习", character: "学习", pinyin: "xué xí", definition: "study; learn" },
  { id: "hsk1-word-学校", character: "学校", pinyin: "xué xiào", definition: "school" },
  { id: "hsk1-word-一", character: "一", pinyin: "yī", definition: "one" },
  { id: "hsk1-word-一点儿", character: "一点儿", pinyin: "yī diǎn er", definition: "a little; a bit" },
  { id: "hsk1-word-衣服", character: "衣服", pinyin: "yī fu", definition: "clothes" },
  { id: "hsk1-word-医生", character: "医生", pinyin: "yī shēng", definition: "doctor" },
  { id: "hsk1-word-医院", character: "医院", pinyin: "yī yuàn", definition: "hospital" },
  { id: "hsk1-word-椅子", character: "椅子", pinyin: "yǐ zi", definition: "chair" },
  { id: "hsk1-word-有", character: "有", pinyin: "yǒu", definition: "have; there is" },
  { id: "hsk1-word-月", character: "月", pinyin: "yuè", definition: "month; moon" },
  { id: "hsk1-word-在", character: "在", pinyin: "zài", definition: "at; in; on" },
  { id: "hsk1-word-再见", character: "再见", pinyin: "zài jiàn", definition: "goodbye; see you again" },
  { id: "hsk1-word-怎么", character: "怎么", pinyin: "zěn me", definition: "how" },
  { id: "hsk1-word-怎么样", character: "怎么样", pinyin: "zěn me yàng", definition: "how about; how is it" },
  { id: "hsk1-word-这", character: "这", pinyin: "zhè", definition: "this" },
  { id: "hsk1-word-中国", character: "中国", pinyin: "zhōng guó", definition: "China" },
  { id: "hsk1-word-中午", character: "中午", pinyin: "zhōng wǔ", definition: "noon" },
  { id: "hsk1-word-住", character: "住", pinyin: "zhù", definition: "live; reside" },
  { id: "hsk1-word-桌子", character: "桌子", pinyin: "zhuō zi", definition: "table; desk" },
  { id: "hsk1-word-字", character: "字", pinyin: "zì", definition: "character; written word" },
  { id: "hsk1-word-做", character: "做", pinyin: "zuò", definition: "do; make" },
  { id: "hsk1-word-坐", character: "坐", pinyin: "zuò", definition: "sit; take (transport)" },
  { id: "hsk1-word-昨天", character: "昨天", pinyin: "zuó tiān", definition: "yesterday" }
]
